AllCops:
  Exclude:
    - bin/*
    - db/schema.rb

# 日本語コメント許可
AsciiComments:
  Enabled: false

# ダブルクォーテーションに統一
StringLiterals:
  EnforcedStyle: double_quotes

# ドキュメンテーション
Style/Documentation:
  Exclude:
    - "db/migrate/**/*"

# ブロック長さ
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"